import { InstrumentPreset } from '../../types/audio';

export const FACTORY_INSTRUMENTS: InstrumentPreset[] = [
  // --- KEYBOARDS & PIANOS ---
  {
    id: 'grand_piano',
    name: 'Concert Grand Piano',
    category: 'keyboards',
    synthesisType: 'additive_piano',
    description: 'Realistic German concert grand piano with multi-harmonic string dispersion and hammer strike transients.',
    origin: 'Germany / Austria',
    icon: 'Piano',
    envelope: { attack: 0.003, decay: 3.5, sustain: 0.05, release: 0.4 },
    filter: { type: 'lowpass', cutoff: 14000, resonance: 0.8, envelopeAmount: 0.4 },
    vibrato: { rate: 5.5, depth: 0.0, delay: 0.5 },
    portamento: 0,
    harmonics: 0.85,
    resonanceTone: 0.65,
    noiseAmount: 0.15,
  },
  {
    id: 'rhodes_mark1',
    name: 'Vintage Rhodes Mark I',
    category: 'keyboards',
    synthesisType: 'fm_epiano',
    description: 'Classic 1970s electric piano with bell-like tine harmonics, warm bark, and vintage preamp warmth.',
    origin: 'United States',
    icon: 'Radio',
    envelope: { attack: 0.005, decay: 2.8, sustain: 0.25, release: 0.35 },
    filter: { type: 'lowpass', cutoff: 8500, resonance: 1.2, envelopeAmount: 0.5 },
    vibrato: { rate: 4.8, depth: 0.15, delay: 0.1 },
    portamento: 0,
    harmonics: 0.72,
    resonanceTone: 0.8,
    noiseAmount: 0.08,
  },
  {
    id: 'hammond_b3',
    name: 'Hammond B3 Drawbar Organ',
    category: 'keyboards',
    synthesisType: 'organ_drawbars',
    description: 'Iconic tonewheel drawbar organ with authentic 9-harmonic overtone control and key-click percussion.',
    origin: 'United States',
    icon: 'Disc',
    envelope: { attack: 0.001, decay: 0.0, sustain: 1.0, release: 0.05 },
    filter: { type: 'lowpass', cutoff: 16000, resonance: 0.5, envelopeAmount: 0.0 },
    vibrato: { rate: 6.2, depth: 0.2, delay: 0.0 },
    portamento: 0,
    harmonics: 0.9,
    resonanceTone: 0.5,
    noiseAmount: 0.25,
    drawbars: [8, 8, 8, 0, 0, 0, 4, 6, 8],
  },
  {
    id: 'celesta',
    name: 'Celestial Celesta',
    category: 'keyboards',
    synthesisType: 'kalimba_tines',
    description: 'Ethereal struck steel plate bells with pure crystalline harmonics and shimmering sustain.',
    origin: 'France',
    icon: 'Sparkles',
    envelope: { attack: 0.001, decay: 2.2, sustain: 0.0, release: 0.6 },
    filter: { type: 'lowpass', cutoff: 18000, resonance: 2.5, envelopeAmount: 0.2 },
    vibrato: { rate: 5.0, depth: 0.05, delay: 0.3 },
    portamento: 0,
    harmonics: 0.95,
    resonanceTone: 0.9,
    noiseAmount: 0.1,
  },

  // --- WORLD & FOLK ---
  {
    id: 'indian_sitar',
    name: 'Royal Indian Sitar',
    category: 'world',
    synthesisType: 'karplus_sitar',
    description: 'Traditional Indian sitar with authentic buzzing jawari flat bridge, sympathetic resonance, and microtonal bends.',
    origin: 'India (Hindustani)',
    icon: 'Music',
    envelope: { attack: 0.002, decay: 3.0, sustain: 0.1, release: 0.5 },
    filter: { type: 'bandpass', cutoff: 3200, resonance: 4.5, envelopeAmount: 0.6 },
    vibrato: { rate: 6.0, depth: 0.35, delay: 0.15 },
    portamento: 0.08,
    harmonics: 0.95,
    resonanceTone: 0.98,
    noiseAmount: 0.3,
  },
  {
    id: 'japanese_koto',
    name: 'Japanese 13-String Koto',
    category: 'world',
    synthesisType: 'karplus_koto',
    description: 'Ancient Japanese zither with high-tension silk strings, crisp ivory plectrum pluck, and paulownia wood body.',
    origin: 'Japan',
    icon: 'Flame',
    envelope: { attack: 0.001, decay: 2.4, sustain: 0.02, release: 0.4 },
    filter: { type: 'lowpass', cutoff: 9500, resonance: 2.2, envelopeAmount: 0.7 },
    vibrato: { rate: 5.2, depth: 0.2, delay: 0.2 },
    portamento: 0.04,
    harmonics: 0.88,
    resonanceTone: 0.85,
    noiseAmount: 0.2,
  },
  {
    id: 'chinese_erhu',
    name: 'Chinese Master Erhu',
    category: 'world',
    synthesisType: 'bowed_erhu',
    description: 'Expressive two-string bowed Chinese spike fiddle with python skin resonator and vocal weeping tone.',
    origin: 'China',
    icon: 'Activity',
    envelope: { attack: 0.08, decay: 0.1, sustain: 0.9, release: 0.25 },
    filter: { type: 'bandpass', cutoff: 2400, resonance: 3.8, envelopeAmount: 0.3 },
    vibrato: { rate: 6.5, depth: 0.45, delay: 0.1 },
    portamento: 0.1,
    harmonics: 0.9,
    resonanceTone: 0.92,
    noiseAmount: 0.35,
  },
  {
    id: 'middle_eastern_oud',
    name: 'Arabic Master Oud',
    category: 'world',
    synthesisType: 'plucked_oud',
    description: 'Fretless 11-string Middle Eastern pear-shaped lute with rich warm low end and risha feather pluck attack.',
    origin: 'Middle East / North Africa',
    icon: 'Feather',
    envelope: { attack: 0.003, decay: 1.8, sustain: 0.05, release: 0.3 },
    filter: { type: 'lowpass', cutoff: 6500, resonance: 1.5, envelopeAmount: 0.5 },
    vibrato: { rate: 5.8, depth: 0.25, delay: 0.18 },
    portamento: 0.06,
    harmonics: 0.78,
    resonanceTone: 0.88,
    noiseAmount: 0.25,
  },
  {
    id: 'african_kalimba',
    name: 'African Mbira / Kalimba',
    category: 'world',
    synthesisType: 'kalimba_tines',
    description: 'Resonant thumb piano with spring steel tines mounted on an African hardwood soundboard box.',
    origin: 'Zimbabwe / Congo',
    icon: 'Compass',
    envelope: { attack: 0.001, decay: 1.6, sustain: 0.0, release: 0.3 },
    filter: { type: 'lowpass', cutoff: 11000, resonance: 2.0, envelopeAmount: 0.4 },
    vibrato: { rate: 4.5, depth: 0.08, delay: 0.25 },
    portamento: 0,
    harmonics: 0.82,
    resonanceTone: 0.9,
    noiseAmount: 0.15,
  },
  {
    id: 'andean_pan_flute',
    name: 'Andean Bamboo Pan Flute',
    category: 'world',
    synthesisType: 'flute_wind',
    description: 'Acoustic Andean Zampona bamboo pipes with airy breath turbulence and harmonic overblowing.',
    origin: 'South America (Andes)',
    icon: 'Wind',
    envelope: { attack: 0.06, decay: 0.2, sustain: 0.85, release: 0.3 },
    filter: { type: 'bandpass', cutoff: 1800, resonance: 5.0, envelopeAmount: 0.4 },
    vibrato: { rate: 5.5, depth: 0.3, delay: 0.15 },
    portamento: 0.05,
    harmonics: 0.65,
    resonanceTone: 0.95,
    noiseAmount: 0.5,
  },
  {
    id: 'highland_bagpipes',
    name: 'Scottish Highland Bagpipes',
    category: 'world',
    synthesisType: 'bagpipe_drone',
    description: 'Great Highland bagpipe with continuous bass and tenor harmonic drones and biting reed chanter melody.',
    origin: 'Scotland',
    icon: 'Volume2',
    envelope: { attack: 0.01, decay: 0.0, sustain: 1.0, release: 0.15 },
    filter: { type: 'lowpass', cutoff: 8000, resonance: 3.0, envelopeAmount: 0.2 },
    vibrato: { rate: 6.8, depth: 0.15, delay: 0.0 },
    portamento: 0.03,
    harmonics: 0.92,
    resonanceTone: 0.9,
    noiseAmount: 0.3,
  },
  {
    id: 'celtic_harp',
    name: 'Celtic Concert Harp',
    category: 'world',
    synthesisType: 'harp_plucked',
    description: 'Pristine 34-string Celtic folk harp with pure ringing harmonics and lush soundboard decay.',
    origin: 'Ireland',
    icon: 'Anchor',
    envelope: { attack: 0.002, decay: 3.8, sustain: 0.08, release: 0.8 },
    filter: { type: 'lowpass', cutoff: 13000, resonance: 1.2, envelopeAmount: 0.4 },
    vibrato: { rate: 4.8, depth: 0.05, delay: 0.4 },
    portamento: 0,
    harmonics: 0.84,
    resonanceTone: 0.92,
    noiseAmount: 0.1,
  },
  {
    id: 'steel_tongue_drum',
    name: 'Mystic Steel Tongue Drum',
    category: 'world',
    synthesisType: 'kalimba_tines',
    description: 'Harmonic steel handpan with deep meditative overtones and circular bell acoustics.',
    origin: 'Global / Contemporary',
    icon: 'Sun',
    envelope: { attack: 0.002, decay: 4.2, sustain: 0.05, release: 0.9 },
    filter: { type: 'lowpass', cutoff: 7500, resonance: 3.5, envelopeAmount: 0.5 },
    vibrato: { rate: 3.8, depth: 0.1, delay: 0.2 },
    portamento: 0,
    harmonics: 0.8,
    resonanceTone: 0.96,
    noiseAmount: 0.08,
  },

  // --- STRINGS & ORCHESTRAL ---
  {
    id: 'stradivarius_violin',
    name: 'Stradivarius Solo Violin',
    category: 'strings',
    synthesisType: 'violin_bowed',
    description: 'Master Italian solo violin with rich rosin bowing friction, passionate vibrato, and dynamic spruce resonance.',
    origin: 'Italy (Cremona)',
    icon: 'Activity',
    envelope: { attack: 0.05, decay: 0.1, sustain: 0.92, release: 0.35 },
    filter: { type: 'bandpass', cutoff: 3100, resonance: 3.2, envelopeAmount: 0.4 },
    vibrato: { rate: 6.2, depth: 0.4, delay: 0.12 },
    portamento: 0.07,
    harmonics: 0.92,
    resonanceTone: 0.9,
    noiseAmount: 0.28,
  },
  {
    id: 'orchestral_cello',
    name: 'Symphony Cello Section',
    category: 'strings',
    synthesisType: 'cello_bowed',
    description: 'Deep, resonant cello with dark wood body acoustic cavity and soaring expressive vibrato.',
    origin: 'Europe',
    icon: 'Radio',
    envelope: { attack: 0.07, decay: 0.15, sustain: 0.95, release: 0.45 },
    filter: { type: 'lowpass', cutoff: 4500, resonance: 2.0, envelopeAmount: 0.35 },
    vibrato: { rate: 5.6, depth: 0.35, delay: 0.15 },
    portamento: 0.08,
    harmonics: 0.85,
    resonanceTone: 0.94,
    noiseAmount: 0.2,
  },
  {
    id: 'symphony_brass',
    name: 'Orchestral Brass Ensemble',
    category: 'strings',
    synthesisType: 'brass_ensemble',
    description: 'Powerful French horn and trombone orchestral section with dynamic bell opening filter envelope.',
    origin: 'Vienna',
    icon: 'Volume2',
    envelope: { attack: 0.04, decay: 0.2, sustain: 0.85, release: 0.3 },
    filter: { type: 'lowpass', cutoff: 6000, resonance: 2.8, envelopeAmount: 0.65 },
    vibrato: { rate: 5.2, depth: 0.18, delay: 0.25 },
    portamento: 0.04,
    harmonics: 0.9,
    resonanceTone: 0.85,
    noiseAmount: 0.15,
  },

  // --- SYNTHS & BASS ---
  {
    id: 'moog_sub37',
    name: 'Moog Sub 37 Analog Bass',
    category: 'synths',
    synthesisType: 'analog_bass',
    description: 'Legendary 24dB ladder filter analog monosynth with punchy dual-saw sub-oscillator and snappy envelope.',
    origin: 'United States',
    icon: 'Zap',
    envelope: { attack: 0.002, decay: 0.4, sustain: 0.3, release: 0.15 },
    filter: { type: 'lowpass', cutoff: 3500, resonance: 6.5, envelopeAmount: 0.8 },
    vibrato: { rate: 5.0, depth: 0.05, delay: 0.3 },
    portamento: 0.05,
    harmonics: 0.85,
    resonanceTone: 0.8,
    noiseAmount: 0.05,
  },
  {
    id: 'juno_106_pad',
    name: 'Juno-106 Lush Shimmer Pad',
    category: 'synths',
    synthesisType: 'juno_pad',
    description: 'Warm analog polysynth pad with iconic bucket-brigade stereo chorus and smooth slow filter swell.',
    origin: 'Japan',
    icon: 'Cloud',
    envelope: { attack: 0.45, decay: 1.2, sustain: 0.8, release: 1.4 },
    filter: { type: 'lowpass', cutoff: 5200, resonance: 2.2, envelopeAmount: 0.4 },
    vibrato: { rate: 4.2, depth: 0.2, delay: 0.4 },
    portamento: 0.04,
    harmonics: 0.88,
    resonanceTone: 0.75,
    noiseAmount: 0.02,
  },
  {
    id: 'sub_808_boom',
    name: '808 Deep Sub & Slide Bass',
    category: 'synths',
    synthesisType: 'sub_808',
    description: 'Earth-shaking modern hip hop / trap 808 sine sub bass with pitch punch envelope and glide.',
    origin: 'Atlanta / Global',
    icon: 'Sliders',
    envelope: { attack: 0.001, decay: 1.2, sustain: 0.6, release: 0.4 },
    filter: { type: 'lowpass', cutoff: 950, resonance: 1.0, envelopeAmount: 0.3 },
    vibrato: { rate: 3.0, depth: 0.0, delay: 0.0 },
    portamento: 0.12,
    harmonics: 0.4,
    resonanceTone: 0.95,
    noiseAmount: 0.02,
  },

  // --- GUITARS & PLUCKS ---
  {
    id: 'flamenco_guitar',
    name: 'Spanish Flamenco Nylon Guitar',
    category: 'guitars',
    synthesisType: 'acoustic_guitar',
    description: 'Crisp Spanish cypress flamenco guitar with rapid fingernail rasgueado snap and percussive body resonance.',
    origin: 'Spain (Andalusia)',
    icon: 'Play',
    envelope: { attack: 0.001, decay: 2.0, sustain: 0.05, release: 0.25 },
    filter: { type: 'lowpass', cutoff: 12000, resonance: 1.8, envelopeAmount: 0.6 },
    vibrato: { rate: 6.0, depth: 0.22, delay: 0.15 },
    portamento: 0.03,
    harmonics: 0.86,
    resonanceTone: 0.88,
    noiseAmount: 0.2,
  },
  {
    id: 'shimmer_12string',
    name: '12-String Shimmer Acoustic',
    category: 'guitars',
    synthesisType: 'acoustic_guitar',
    description: 'Sparkling steel-string 12-string guitar with paired octave and unison chime strings.',
    origin: 'United States',
    icon: 'Sparkles',
    envelope: { attack: 0.002, decay: 2.8, sustain: 0.08, release: 0.4 },
    filter: { type: 'lowpass', cutoff: 15000, resonance: 1.2, envelopeAmount: 0.45 },
    vibrato: { rate: 4.8, depth: 0.08, delay: 0.3 },
    portamento: 0,
    harmonics: 0.95,
    resonanceTone: 0.85,
    noiseAmount: 0.15,
  },

  // --- WORLD PERCUSSION ---
  {
    id: 'indian_tabla',
    name: 'Indian Tabla (Dayan & Bayan)',
    category: 'percussion',
    synthesisType: 'tabla_world',
    description: 'Tuned Indian percussion set with pitch-modulated bass Bayan and high ringing resonant Dayan bell strike.',
    origin: 'India',
    icon: 'Circle',
    envelope: { attack: 0.001, decay: 0.9, sustain: 0.0, release: 0.2 },
    filter: { type: 'bandpass', cutoff: 1400, resonance: 6.0, envelopeAmount: 0.7 },
    vibrato: { rate: 8.0, depth: 0.1, delay: 0.0 },
    portamento: 0.08,
    harmonics: 0.82,
    resonanceTone: 0.98,
    noiseAmount: 0.4,
  },
];
